export const serveInfoData = []

export const serveInfoOneData = [
  {
    structName: 'root',
    id: '11',
    parentId: '',
    index: 0,
    structAlias: '根节点',
    children: [
      { structName: 'request', id: '12', parentId: '11', children: [], structAlias: '请求信息' },
      { structName: 'response', id: '13', parentId: '11', children: [], structAlias: '响应信息' },
    ],
  },
]
// 渲染到双层级树结构下的模拟后端数据
export const resDataDouble = [
  {
    structCusName: 'root',
    structName: 'root',
    structAlias: '根节点',
    id: '1',
    parentId: '',
    type: '',
    typeCus: '',
    children: [
      {
        structCusName: 'request',
        structName: 'request',
        structAlias: '请求',
        id: '2',
        parentId: '1',
        type: '',
        typeCus: '',
        xpath: '/request',
        children: [
          {
            structCusName: '',
            structName: 'userId',
            structAlias: '用户id',
            id: '4',
            parentId: '2',
            type: 'String',
            typeCus: '',
            children: [],
            xpath: '/request/userName',
          },
          {
            structCusName: '',
            structName: 'userName',
            structAlias: '用户名称',
            id: '5',
            parentId: '2',
            type: 'String',
            typeCus: '',
            children: [],
            xpath: '/request/userName',
          },
          {
            structCusName: '',
            structName: 'userAge',
            structAlias: '用户年龄',
            id: '6',
            parentId: '2',
            typeCus: '',
            children: [],
            xpath: '/request/userName',
          },
        ],
      },
      {
        structCusName: 'response',
        structName: 'response',
        structAlias: '响应',
        id: '3',
        parentId: '1',
        type: '',
        typeCus: '',
        xpath: '/response',
        children: [
          {
            structCusName: '',
            structName: 'userId',
            structAlias: '用户id',
            id: '44',
            parentId: '3',
            type: 'String',
            typeCus: '',
            xpath: '/response/userName',
            children: [],
          },
          {
            structCusName: '',
            structName: 'userName',
            structAlias: '用户名称',
            xpath: '/response/userName',
            id: '55',
          },
        ],
      },
    ],
    xpath: '/',
  },
]
//做点击英文名称展示的树形选择框里的数据
export const resMappingDouble = [
  {
    structName: 'root',
    structAlias: '根节点',
    id: '1',
    parentId: '',
    type: '',
    children: [
      {
        structName: 'request',
        structAlias: '请求',
        id: '2',
        parentId: '1',
        type: '',
        xpath: '/request',
        children: [
          {
            structName: 'userId',
            structAlias: '用户id',
            id: '4',
            parentId: '2',
            type: 'String',
            xpath: '/request/userId',
          },
          {
            structName: 'userName',
            structAlias: '用户名称',
            id: '5',
            parentId: '2',
            type: 'String',
            xpath: '/request/userName',
          },
          {
            structName: 'userAge',
            structAlias: '用户年龄',
            id: '6',
            parentId: '2',
            type: 'Integer',
            xpath: '/request/userAge',
          },
        ],
      },
      {
        structName: 'response',
        structAlias: '响应',
        id: '3',
        parentId: '1',
        type: '',
        xpath: '/response',
        children: [
          {
            structName: 'userId',
            structAlias: '用户id',
            id: '41',
            parentId: '3',
            type: 'String',
            xpath: '/response/userId',
          },
          {
            structName: 'userName',
            structAlias: '用户名称',
            id: '521',
            parentId: '3',
            type: 'String',
            xpath: '/response/userName',
          },
        ],
      },
    ],
    xpath: '/',
  },
]
